controllers/notes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_security import login_required, current_user
from sqlalchemy import func

from forms import NoteForm
from models import db, Note, Logbook, Log
from utils import check_default_profile

bp_notes = Blueprint("bp_notes", __name__)


@bp_notes.route("/notes", methods=["GET"])
@login_required
@check_default_profile
def notes():
    pcfg = {"title": "My notes"}

    _notes = Note.query.filter(Note.user_id == current_user.id).all()
    logbooks = (
        db.session.query(Logbook.id, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )

    return render_template("notes/view.jinja2", pcfg=pcfg, notes=_notes, logbooks=logbooks)


@bp_notes.route("/notes/<int:note_id>/edit", methods=["GET", "POST"])
@login_required
@check_default_profile
def edit(note_id):
    pcfg = {"title": "Edit my notes"}

    a = Note.query.filter(Note.user_id == current_user.id, Note.id == note_id).first()
    if not a:
        flash("Note not found", "error")
        return redirect(url_for("bp_notes.notes"))

    form = NoteForm(request.form, obj=a)

    if form.validate_on_submit():
        a.title = form.title.data
        a.cat = form.cat.data
        a.note = form.note.data

        db.session.commit()

        flash("Success saving note: {0}".format(a.title), "success")
        return redirect(url_for("bp_notes.notes"))

    logbooks = Logbook.query.filter(Logbook.user_id == current_user.id).all()

    return render_template("notes/edit.jinja2", pcfg=pcfg, form=form, note=a, note_id=note_id, logbooks=logbooks)


@bp_notes.route("/notes/new", methods=["GET", "POST"])
@login_required
@check_default_profile
def new():
    pcfg = {"title": "New note"}

    form = NoteForm()

    if form.validate_on_submit():
        a = Note()
        a.title = form.title.data
        a.cat = form.cat.data
        a.note = form.note.data
        a.user_id = current_user.id

        db.session.add(a)
        db.session.commit()

        flash("Success updating note: {0}".format(a.title), "success")
        return redirect(url_for("bp_notes.notes"))

    logbooks = (
        db.session.query(Logbook.id, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )
    return render_template("notes/new.jinja2", pcfg=pcfg, form=form, logbooks=logbooks)


@bp_notes.route("/notes/<int:note_id>/delete", methods=["GET", "DELETE", "PUT"])
@login_required
@check_default_profile
def delete(note_id):
    note = Note.query.filter(Note.user_id == current_user.id, Note.id == note_id).first()
    if not note:
        flash("Note not found", "error")
        return redirect(url_for("bp_notes.notes"))

    db.session.delete(note)
    db.session.commit()

    return redirect(url_for("bp_notes.notes"))

templates/notes/_single.jinja2
<div class="row">
    <div class="col-lg-12 single-note">
        <div class="well small well-sm well-ultra-sm">
            <footer>
                <a href="{{ url_for('bp_notes.edit', note_id=note.id) }}" class="btn btn-primary btn-sm">edit</a>
                <a href="{{ url_for('bp_notes.delete', note_id=note.id) }}" class="btn btn-danger btn-sm delete_link">delete</a>

                <span class="label label-default">Category</span>
                {{ note.cat }}
                <span class="label label-default">Date</span>
                {{ note.timestamp | localize }}
                <span class="label label-default">Title</span>
                {{ note.title }}

            </footer>
        </div>
        <div class="summary">{{ note.note }}</div>
    </div>
</div>

templates/notes/edit.jinja2
{% extends "layout.jinja2" %}
{% import 'bootstrap/form.html' as bf4 %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h3>Edit note: {{ note.title }} <a class="btn btn-sm btn-warning" href="{{ url_for('bp_notes.notes') }}">Cancel</a></h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12">
            {{ bf4.render_form(form, action=url_for('bp_notes.edit', note_id=note.id), horizontal_columns=('lg', 2, 5), form_type='horizontal', button_map={'submit': 'success'}) }}
        </div>
    </div>
{% endblock %}

templates/notes/new.jinja2
{% extends "layout.jinja2" %}
{% import 'bootstrap/form.html' as bf4 %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h3>New note <a class="btn btn-sm btn-warning" href="{{ url_for('bp_notes.notes') }}">Cancel</a></h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12">
            {{ bf4.render_form(form, action=url_for('bp_notes.new'), horizontal_columns=('lg', 2, 4), form_type='horizontal', button_map={'submit': 'success'}) }}
        </div>
    </div>
{% endblock %}

templates/notes/view.jinja2
{% extends "layout.jinja2" %}

{% block content %}
<div class="row">
    <div class="col-lg-6">
        <h3>
            {{ current_user.name }}'s notes
            <a href="{{ url_for('bp_notes.new') }}" class="btn btn-success btn-sm">new</a>
        </h3>

    {% for note in notes %}
        {% with note=note %}
            {% include 'notes/_single.jinja2' %}
        {% endwith %}
    {% endfor %}

    </div>
</div>
{% endblock %}