controllers/admin.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_security import login_required

from forms import ConfigForm
from models import db, Logging, Config
from utils import check_default_profile, is_admin

bp_admin = Blueprint("bp_admin", __name__)


@bp_admin.route("/admin/logs", methods=["GET"])
@login_required
@check_default_profile
def logs():
    if not is_admin():
        return redirect(url_for("bp_home.home"))
    pcfg = {"title": "Application Logs"}
    _logs = Logging.query.order_by(Logging.timestamp.desc()).limit(100).all()
    return render_template("admin/logs.jinja2", pcfg=pcfg, logs=_logs)


@bp_admin.route("/admin/config", methods=["GET", "POST"])
@login_required
@check_default_profile
def config():
    if not is_admin():
        return redirect(url_for("bp_main.home"))

    pcfg = {"title": "Application Config"}

    _config = Config.query.one()
    if not _config:
        flash("Config not found", "error")
        return redirect(url_for("bp_main.home"))

    form = ConfigForm(request.form, obj=_config)

    if form.validate_on_submit():
        _config.clublog_api_key = form.clublog_api_key.data
        _config.eqsl_download_url = form.eqsl_download_url.data
        _config.eqsl_rcvd_mark = form.eqsl_rcvd_mark.data
        _config.eqsl_upload_url = form.eqsl_upload_url.data
        _config.lotw_download_url = form.lotw_download_url.data
        _config.lotw_upload_url = form.lotw_upload_url.data
        _config.lotw_login_url = form.lotw_login_url.data
        _config.lotw_rcvd_mark = form.lotw_rcvd_mark.data

        db.session.commit()
        flash("Configuration updated", "info")
        return redirect(url_for("bp_admin.config"))

    return render_template("admin/config.jinja2", pcfg=pcfg, form=form)

controllers/main.py
from flask import Blueprint, render_template, flash
from flask_security import current_user
from sqlalchemy import func

from models import db, User, Logbook, Log, DxccEntities, DxccExceptions, DxccPrefixes

bp_main = Blueprint("bp_main", __name__)


# Show public logbooks
@bp_main.route("/")
def home():
    # Sanity check
    _dp = db.session.query(DxccPrefixes.id).count()
    _dx = db.session.query(DxccExceptions.id).count()
    _de = db.session.query(DxccEntities.id).count()
    # Count as of 25/08/16 was:
    # 3665     16435     401
    # check are lowered to avoid changing them maybe too frequently
    if _dp < 3500 or _dx < 16300 or _de < 300:
        flash("DXCC Tables are empty, check manual", "error")
        # abort(500)

    pcfg = {"title": "AHRL - Another Ham Radio Log"}
    users = User.query.all()

    logbooks = None
    if current_user.is_authenticated:
        logbooks = (
            db.session.query(Logbook.id, Logbook.slug, Logbook.name, func.count(Log.id))
            .join(Log)
            .filter(Logbook.user_id == current_user.id)
            .group_by(Logbook.id)
            .all()
        )

    return render_template("home.jinja2", pcfg=pcfg, users=users, logbooks=logbooks)


@bp_main.route("/about")
def about():
    pcfg = {"title": "About AHRL - Another Ham Radio Log"}
    return render_template("about.jinja2", pcfg=pcfg)

controllers/notes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_security import login_required, current_user
from sqlalchemy import func

from forms import NoteForm
from models import db, Note, Logbook, Log
from utils import check_default_profile

bp_notes = Blueprint("bp_notes", __name__)


@bp_notes.route("/notes", methods=["GET"])
@login_required
@check_default_profile
def notes():
    pcfg = {"title": "My notes"}

    _notes = Note.query.filter(Note.user_id == current_user.id).all()
    logbooks = (
        db.session.query(Logbook.id, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )

    return render_template("notes/view.jinja2", pcfg=pcfg, notes=_notes, logbooks=logbooks)


@bp_notes.route("/notes/<int:note_id>/edit", methods=["GET", "POST"])
@login_required
@check_default_profile
def edit(note_id):
    pcfg = {"title": "Edit my notes"}

    a = Note.query.filter(Note.user_id == current_user.id, Note.id == note_id).first()
    if not a:
        flash("Note not found", "error")
        return redirect(url_for("bp_notes.notes"))

    form = NoteForm(request.form, obj=a)

    if form.validate_on_submit():
        a.title = form.title.data
        a.cat = form.cat.data
        a.note = form.note.data

        db.session.commit()

        flash("Success saving note: {0}".format(a.title), "success")
        return redirect(url_for("bp_notes.notes"))

    logbooks = Logbook.query.filter(Logbook.user_id == current_user.id).all()

    return render_template("notes/edit.jinja2", pcfg=pcfg, form=form, note=a, note_id=note_id, logbooks=logbooks)


@bp_notes.route("/notes/new", methods=["GET", "POST"])
@login_required
@check_default_profile
def new():
    pcfg = {"title": "New note"}

    form = NoteForm()

    if form.validate_on_submit():
        a = Note()
        a.title = form.title.data
        a.cat = form.cat.data
        a.note = form.note.data
        a.user_id = current_user.id

        db.session.add(a)
        db.session.commit()

        flash("Success updating note: {0}".format(a.title), "success")
        return redirect(url_for("bp_notes.notes"))

    logbooks = (
        db.session.query(Logbook.id, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )
    return render_template("notes/new.jinja2", pcfg=pcfg, form=form, logbooks=logbooks)


@bp_notes.route("/notes/<int:note_id>/delete", methods=["GET", "DELETE", "PUT"])
@login_required
@check_default_profile
def delete(note_id):
    note = Note.query.filter(Note.user_id == current_user.id, Note.id == note_id).first()
    if not note:
        flash("Note not found", "error")
        return redirect(url_for("bp_notes.notes"))

    db.session.delete(note)
    db.session.commit()

    return redirect(url_for("bp_notes.notes"))

controllers/qsos.py
import datetime
import os
from calendar import monthrange
from libqth import is_valid_qth, qth_to_coords

import pytz
from flask import Blueprint, render_template, request, redirect, url_for, Response, json, flash, current_app
from flask_security import login_required, current_user
from flask_uploads import UploadSet, IMAGES
from geohelper import distance, bearing
from sqlalchemy import func
from sqlalchemy.orm import Bundle
from sqlalchemy.sql.expression import case

from forms import QsoForm, EditQsoForm, FilterLogbookBandMode, PictureForm, AdvSearchForm
from libjambon import band_to_frequency, geo_bearing_star, get_dxcc_from_clublog_or_database
from models import db, User, Log, Band, Mode, Logbook, Picture
from models import ham_country_grid_coords, cutename
from utils import InvalidUsage, dt_utc_to_user_tz, check_default_profile

from pyhamqth import HamQTH, HamQTHQueryFailed

bp_qsos = Blueprint("bp_qsos", __name__)

pictures = UploadSet("pictures", IMAGES)


@bp_qsos.route("/user/<string:username>/logbook/<string:logbook_slug>", methods=["GET"])
@check_default_profile
def logbook(username, logbook_slug):
    user = User.query.filter(User.name == username).first()
    if not user:
        flash("User not found", "error")
        return redirect(url_for("bp_main.home"))

    try:
        page = int(request.args.get("page", 1))
    except ValueError:
        page = 1

    pcfg = {"title": "{0}'s ({1}) logbook".format(user.name, user.callsign)}

    _logbook = Logbook.query.filter(Logbook.slug == logbook_slug, Logbook.user_id == user.id).first()
    if not _logbook:
        flash("Logbook not found", "error")
        return redirect(url_for("bp_logbooks.logbooks", user=user.name))

    if not _logbook.public and not current_user.is_authenticated:
        flash("Logbook not found", "error")
        return redirect(url_for("bp_logbooks.logbooks", user=user.name))

    if not _logbook.public and _logbook.user_id != current_user.id:
        flash("Logbook not found", "error")
        return redirect(url_for("bp_logbooks.logbooks", user=user.name))

    if is_valid_qth(user.locator, 6):
        uqth = user.qth_to_coords()
    else:
        flash("User gridsquare is invalid")
        return redirect(url_for("bp_logbooks.logbooks", user=user.name))

    d = datetime.datetime.utcnow()
    mr_m = monthrange(d.year, d.month)
    mr_y = monthrange(d.year, 12)

    d_month_start = datetime.datetime(d.year, d.month, 0o1, 00, 00, 00, tzinfo=pytz.timezone("UTC"))
    d_month_end = datetime.datetime(d.year, d.month, mr_m[1], 23, 59, 59, tzinfo=pytz.timezone("UTC"))
    d_year_start = datetime.datetime(d.year, 0o1, 0o1, 00, 00, 00, tzinfo=pytz.timezone("UTC"))
    d_year_end = datetime.datetime(d.year, 12, mr_y[1], 23, 59, 59, tzinfo=pytz.timezone("UTC"))
    cntry_worked = (
        db.session.query(Log.country)
        .filter(Log.user_id == user.id, Log.logbook_id == _logbook.id)
        .distinct(Log.country)
        .count()
    )

    # Form filter display thing and QSOs filtering
    filter_form = FilterLogbookBandMode()
    q_mode = None
    q_band = None
    rq_mode = request.args.get("mode", None)
    rq_band = request.args.get("band", None)

    if rq_mode or rq_mode != "all":
        q_mode = Mode.query.filter(Mode.submode == rq_mode)
        if q_mode.count() == 1:
            q_mode = q_mode.first()
        else:
            q_mode = None
    if rq_band or rq_band != "all":
        q_band = Band.query.filter(Band.modes.is_(None), Band.start.is_(None), Band.name == rq_band)
        if q_band.count() == 1:
            q_band = q_band.first()
        else:
            q_band = None

    # Form choices building
    filter_modes = []
    _a_logs = Bundle("log", Log.mode_id)
    _b_modes = Bundle("modes", Mode.id, Mode.mode, Mode.submode)
    for _modes, _logs in (
        db.session.query(_b_modes, _a_logs)
        .join(Mode.logs)
        .filter(Log.user_id == user.id, Log.logbook_id == _logbook.id)
        .group_by(_a_logs, _b_modes)
        .all()
    ):
        filter_modes.append([_modes.id, "{0} - {1}".format(_modes.mode, _modes.submode)])

    filter_bands = []
    _a_logs = Bundle("log", Log.band_id)
    _b_bands = Bundle("bands", Band.id, Band.name)
    for _bands, _logs in (
        db.session.query(_b_bands, _a_logs)
        .join(Band.logs)
        .filter(Log.user_id == user.id, Log.logbook_id == _logbook.id)
        .group_by(_a_logs, _b_bands)
        .all()
    ):
        filter_bands.append([_bands.name, _bands.name])

    filter_modes.insert(0, ["all", "All modes"])
    filter_bands.insert(0, ["all", "All bands"])

    filter_form.mode.choices = filter_modes
    filter_form.mode.data = rq_mode or "all"
    filter_form.band.choices = filter_bands
    filter_form.band.data = rq_band or "all"

    bq = Log.query.filter(User.id == user.id, Log.logbook_id == _logbook.id)

    if q_mode and not q_band:
        fquery = bq.filter(Log.mode_id == q_mode.id)
    elif not q_mode and q_band:
        fquery = bq.filter(Log.band_id == q_band.id)
    elif q_mode and q_band:
        fquery = bq.filter(Log.mode_id == q_mode.id, Log.band_id == q_band.id)
    else:
        fquery = bq

    qsos = fquery.paginate(page=page, per_page=20)

    # Column of stats
    stats = {
        "qsos": {
            "total": db.session.query(Log.id).filter(Log.user_id == user.id, Log.logbook_id == _logbook.id).count(),
            "month": db.session.query(Log.id)
            .filter(
                Log.user_id == user.id, Log.time_on.between(d_month_start, d_month_end), Log.logbook_id == _logbook.id
            )
            .count(),
            "year": db.session.query(Log.id)
            .filter(
                Log.user_id == user.id, Log.time_on.between(d_year_start, d_year_end), Log.logbook_id == _logbook.id
            )
            .count(),
        },
        "countries": {"worked": cntry_worked, "needed": 340 - cntry_worked},
        "qsl": {
            "sent": db.session.query(Log.id)
            .filter(Log.user_id == user.id, Log.qsl_sent == "Y", Log.logbook_id == _logbook.id)
            .count(),
            "received": db.session.query(Log.id)
            .filter(Log.user_id == user.id, Log.qsl_rcvd == "Y", Log.logbook_id == _logbook.id)
            .count(),
            "requested": db.session.query(Log.id)
            .filter(Log.user_id == user.id, Log.qsl_sent == "R", Log.logbook_id == _logbook.id)
            .count(),
        },
    }

    if current_user.is_authenticated:
        logbooks = (
            db.session.query(Logbook.id, Logbook.slug, Logbook.name, func.count(Log.id))
            .join(Log)
            .filter(Logbook.user_id == current_user.id)
            .group_by(Logbook.id)
            .all()
        )
    else:
        logbooks = (
            db.session.query(Logbook.id, Logbook.slug, Logbook.name, func.count(Log.id))
            .join(Log)
            .filter(Logbook.user_id == user.id, Logbook.public.is_(True))
            .group_by(Logbook.id)
            .all()
        )

    return render_template(
        "qsos/logbook.jinja2",
        pcfg=pcfg,
        qsos=qsos,
        user=user,
        logbook=_logbook,
        uqth=uqth,
        stats=stats,
        filter_form=filter_form,
        band=rq_band,
        mode=rq_mode,
        logbooks=logbooks,
    )


@bp_qsos.route("/logbook/<string:logbook_slug>/qsos/new/<string:method>", methods=["GET", "POST"])
@login_required
@check_default_profile
def new(logbook_slug, method):
    if method not in ["live", "manual"]:
        return redirect(url_for("bp_qsos.logbook", user_id=current_user.id))

    pcfg = {"title": "New QSO"}

    form = QsoForm()

    _logbook = Logbook.query.filter(Logbook.slug == logbook_slug, Logbook.user_id == current_user.id).first()
    if not _logbook or _logbook.user_id != current_user.id:
        flash("Logbook not found !", "error")
        return redirect(url_for("bp_logbooks.logbooks", user=current_user.name))

    logbooks = (
        db.session.query(Logbook.id, Logbook.slug, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )

    if form.validate_on_submit():
        a = Log()
        # We get from user input a date with timezone offset (we asume that)
        # We store in database in UTC offset, so first convert to DT then makes aware
        # of the user timezone, and then convert to UTC
        date = form.date.data.strftime("%Y-%m-%d")
        time = form.time.data.strftime("%H:%M:%S")
        date_wo_tz = datetime.datetime.strptime("{0} {1}".format(date, time), "%Y-%m-%d %H:%M:%S")
        date_w_tz = pytz.timezone(current_user.timezone).localize(date_wo_tz)

        a.time_on = date_w_tz.astimezone(pytz.timezone("UTC")).replace(tzinfo=None)
        a.time_off = date_w_tz.astimezone(pytz.timezone("UTC")).replace(tzinfo=None)

        a.call = form.call.data.upper()
        a.freq = form.freq.data
        a.rst_rcvd = form.rst_rcvd.data
        a.rst_sent = form.rst_sent.data
        a.name = form.name.data
        a.comment = form.comment.data
        a.qsl_comment = form.qsl_comment.data
        a.sat_name = form.sat_name.data.upper()
        a.sat_mode = form.sat_mode.data.upper()

        if not form.gridsquare.data or form.gridsquare.data == "":
            cmp_qth = ham_country_grid_coords(a.call)
            if cmp_qth and "qth" in cmp_qth:
                a.cache_gridsquare = cmp_qth["qth"]
        else:
            a.gridsquare = form.gridsquare.data.upper()
            a.cache_gridsquare = a.gridsquare

        a.country = form.country.data
        a.qsl_sent = form.qsl_sent.raw_data[0]
        a.qsl_sent_via = form.qsl_sent_via.raw_data[0]
        a.qsl_via = form.qsl_via.data
        a.eqsl_qsl_sent = form.eqsl_qsl_sent.data
        a.operator = current_user.callsign.upper()
        a.owner_callsign = current_user.callsign.upper()

templates/about.jinja2
{% extends "layout.jinja2" %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <p>AHRL - Another Ham Radio Log is developped by <a href="http://sigpipe.me/" target="_blank">Dashie</a> and is available under MIT license.</p>
        <ul>
            <li>Source code is here : <a href="http://dev.sigpipe.me/DashieHam/AHRL" target="_blank">http://dev.sigpipe.me/DashieHam/AHRL</a></li>
            <li>Issue tracker is here : <a href="http://dev.sigpipe.me/DashieHam/AHRL/issues" target="_blank">http://dev.sigpipe.me/DashieHam/AHRL/issues</a></li>
        </ul>
    </div>
</div>
{% endblock %}

templates/error_page.jinja2
{% extends "layout.jinja2" %}
{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4" role="content">
            <h3>{{ pcfg['error'] }} - {{ pcfg['message'] }} :'(</h3>
            Maybe you can go back to the <a href="{{ url_for('bp_main.home') }}">index</a>.
        </div>
    </div>
{% endblock %}

templates/home.jinja2
{% extends "layout.jinja2" %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h4>You can view the following logbooks:</h4>
        <ul>
            {% for u in users %}
                <li>
                    <a href="{{ url_for('bp_logbooks.logbooks', user=u.name) }}">{{ u.callsign }}, {{ u.name }}</a>
                    <ul>
                    {% for l in u.logbooks %}
                        {% if l.public %}
                        <li>
                            <a href="{{ url_for('bp_qsos.logbook', username=u.name, logbook_slug=l.slug) }}">{{ l.name }}</a> <small>({{ l.callsign }}, {{ l.logs.count() }} qsos{% if l.old %}, old unused{% endif %})</small>
                            {% if current_user.id == l.user.id %}
                            <a href="{{ url_for('bp_tools.adif_export_dl', username=l.user.name, logbook_slug=l.slug) }}" class="btn btn-success btn-sm">adif export</a>
                            {% endif %}
                            <a href="{{ url_for('bp_qsos.logbook_stats', username=l.user.name, logbook_slug=l.slug) }}" class="btn btn-info btn-sm">stats</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/layout.jinja2
{% import "bootstrap/flash.html" as bf %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
    {% block title %}{% if pcfg and pcfg['title'] %}{{ pcfg['title'] }} - AHRL{% else %}AHRL{% endif %}{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <link href="{{ url_for('static', filename='css/fork-awesome.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    {% block styles %}{% endblock %}
  </head>

    <body>

    <nav class="navbar navbar-expand-md navbar-light">
      <a class="navbar-brand" href="{{ url_for('bp_main.home') }}">AHRL</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if current_user.is_authenticated and request.endpoint %}
            <li class="nav-item {% if request.endpoint == 'bp_logbooks.logbooks' %}active{% endif %}"><a class="nav-link" href="{{ url_for('bp_logbooks.logbooks', user=current_user.name) }}">My Logbooks</a></li>
            {% if logbook %}
                <li class="nav-item {% if request.endpoint == 'bp_logbooks.logbooks' %}active{% endif %}"><a class="nav-link" href="{{ url_for('bp_qsos.logbook', username=current_user.name, logbook_slug=logbook.slug) }}">Current Logbook</a></li>
            {% endif %}
            <li class="nav-item {% if request.endpoint.startswith('bp_contacts.') %}active{% endif %}"><a class="nav-link" href="{{ url_for('bp_contacts.contacts') }}">Contacts</a></li>

            {% if logbook and (current_user.id == logbook.user_id) %}
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">QSOs</a>
              <div class="dropdown-menu" aria-labelledby="dropdown_qso">
                <a class="dropdown-item" href="{{ url_for('bp_qsos.new', method='live', logbook_slug=logbook.slug) }}">Live QSO</a>
                <a class="dropdown-item" href="{{ url_for('bp_qsos.new', method='manual', logbook_slug=logbook.slug) }}">Post QSO</a>
              </div>
            </li>
            {% endif %}

            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Notes</a>
              <div class="dropdown-menu" aria-labelledby="dropdown_qso">
                <a class="dropdown-item" href="{{ url_for('bp_notes.notes') }}">View</a>
                <a class="dropdown-item" href="{{ url_for('bp_notes.new') }}">Create</a>
              </div>
            </li>

            {% if logbooks %}
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Statistics</a>
                  <div class="dropdown-menu" aria-labelledby="dropdown_stats">
                      {% for l in logbooks %}
                        <a class="dropdown-item" href="{{ url_for('bp_qsos.logbook_stats', username=current_user.name, logbook_slug=l.slug) }}">For {{ l.name }} <small>({{ l[3] }} qsos)</small></a>
                      {% endfor %}
                  </div>
                </li>
            {% endif %}

          {% else %}
                {% if user %}
                    <li class="nav-item {% if request.endpoint == 'bp_logbooks.logbooks' %}active{% endif %}"><a class="nav-link" href="{{ url_for('bp_logbooks.logbooks', user=user.name) }}">Logbook</a></li>
                    <li class="nav-item dropdown">
                      <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Statistics</a>
                      <div class="dropdown-menu" aria-labelledby="dropdown_logbooks">
                          {% for l in logbooks %}
                            <a class="dropdown-item" href="{{ url_for('bp_qsos.logbook_stats', username=user.name, logbook_slug=l.slug) }}">For {{ l.name }} <small>({{ l[3] }} qsos)</small></a>
                          {% endfor %}
                      </div>
                    </li>
                {% endif %}
          {% endif %}

            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tools</a>
              <div class="dropdown-menu">
                  <a class="dropdown-item" href="{{ url_for('bp_tools.bands_plan') }}">IARU Band Plans</a>
                  <a class="dropdown-item" href="{{ url_for('bp_tools.map') }}">World Map w/day-night</a>
                  {% if current_user.is_authenticated %}
                    <a class="dropdown-item" href="{{ url_for('bp_tools.adif_import') }}">ADIF Import</a>
                  {% endif %}
              </div>
            </li>

            {% if logbook %}
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search</a>
                  <ul id="search-dd" class="dropdown-menu">
                      <li>
                        <div class="row adv-search">
                          <div class="col-md-12">
                              <a href="{{ url_for('bp_qsos.logbook_search_adv', logbook_slug=logbook.slug, username=logbook.user.name) }}">Advanced search page</a>
                          </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <form accept-charset="UTF-8" role="form" class="form-inline" method="get" action="{{ url_for('bp_qsos.logbook_search', logbook_slug=logbook.slug, username=logbook.user.name) }}">
                                    <div class="form-group">
                                        <input class="form-control" type="text" name="q" placeholder="Search term">
                                    </div>
                                    <button type="submit" class="btn btn-info"><i class="fa fa-search" aria-hidden="true"></i></button>
                                </form>
                            </div>
                        </div>
                      </li>
                  </ul>
                </li>
            {% endif %}

        </ul>

        <ul class="navbar-nav ml-auto">
            {% if request.endpoint %}
                <li class="nav-item {% if request.endpoint.startswith('bp_main.about') %}active{% endif %}"><a class="nav-link" href="{{ url_for('bp_main.about') }}">About</a></li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item dropdown">
                      <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Logged as {{ current_user.name }}</a>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown_user">
                          <h6 class="dropdown-header">User</h6>
                          <a class="dropdown-item" href="{{ url_for('bp_users.profile') }}">Profile</a>
                          <a class="dropdown-item" href="{{ url_for('bp_users.logs') }}">Logs</a>
                          {% if is_admin() %}
                              <div class="dropdown-divider"></div>
                              <h6 class="dropdown-header">Admin</h6>
                              <a class="dropdown-item" href="{{ url_for('bp_admin.config') }}">App config</a>
                              <a class="dropdown-item" href="{{ url_for('bp_admin.logs') }}">App logs</a>
                          {% endif %}
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{{ url_for_security('change_password') }}">Change password</a>
                          <a class="dropdown-item" href="{{ url_for_security('logout') }}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    {% if security.registerable %}
                        <li class="nav-item {% if request.endpoint.startswith('security.register') %}active{% endif %}"><a class="nav-link" href="{{ url_for_security('register') }}">Register</a></li>
                    {% endif %}
                    <li class="nav-item {% if request.endpoint.startswith('security.login') %}active{% endif %}"><a class="nav-link" href="{{ url_for_security('login') }}">Login</a></li>
                {% endif %}
            {% endif %}
          </ul>
      </div>
    </nav>

    <main role="main" class="container">
        <div class="row justify-content-center">
            <div class="col-6">{{ bf.flashed_messages(container=False) }}</div>
        </div>

        {% block content %}{% endblock %}
    </main><!-- /.container -->

    <!-- FIXME: footer styling -->
    <footer class="blog-footer">
      <p>AHRL <a href="https://github.com/rhaamo/ahrl">Source code</a></p>
      <p><small>Running version {{ g.cfg['AHRL_VERSION'] }}</small></p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.bootstrap-growl.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/global.js') }}"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>