controllers/users.py
import pytz
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_security import login_required, current_user
from sqlalchemy import func

from forms import UserProfileForm
from models import db, User, Logbook, Log, UserLogging
from utils import check_default_profile

bp_users = Blueprint("bp_users", __name__)


@bp_users.route("/user/logs", methods=["GET"])
@login_required
@check_default_profile
def logs():
    level = request.args.get("level")
    pcfg = {"title": "User Logs"}
    if level:
        _logs = (
            UserLogging.query.filter(UserLogging.level == level.upper(), UserLogging.user_id == current_user.id)
            .order_by(UserLogging.timestamp.desc())
            .limit(100)
            .all()
        )
    else:
        _logs = (
            UserLogging.query.filter(UserLogging.user_id == current_user.id)
            .order_by(UserLogging.timestamp.desc())
            .limit(100)
            .all()
        )
    return render_template("users/user_logs.jinja2", pcfg=pcfg, logs=_logs)


@bp_users.route("/user", methods=["GET"])
@login_required
@check_default_profile
def profile():
    pcfg = {"title": "My Profile"}

    user = User.query.filter(User.id == current_user.id).first()
    if not user:
        flash("User not found", "error")
        return redirect(url_for("bp_main.home"))

    logbooks = (
        db.session.query(Logbook.id, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )
    return render_template("users/profile.jinja2", pcfg=pcfg, user=user, logbooks=logbooks)


@bp_users.route("/user/edit", methods=["GET", "POST"])
@login_required
def edit():
    pcfg = {"title": "Edit my profile"}

    user = User.query.filter(User.id == current_user.id).first()
    if not user:
        flash("User not found", "error")
        return redirect(url_for("bp_main.home"))

    form = UserProfileForm(request.form, obj=user)
    form.timezone.choices = [[str(i), str(i)] for i in pytz.all_timezones]

    if form.validate_on_submit():
        user.callsign = form.callsign.data.upper()
        user.lastname = form.lastname.data
        user.firstname = form.firstname.data
        user.timezone = form.timezone.data
        user.locator = form.locator.data.upper()

        user.lotw_name = form.lotw_name.data
        user.lotw_password = form.lotw_password.data

        user.eqsl_name = form.eqsl_name.data
        user.eqsl_password = form.eqsl_password.data

        user.hamqth_name = form.hamqth_name.data
        user.hamqth_password = form.hamqth_password.data

        user.swl = form.swl.data
        user.zone = form.zone.data

        db.session.commit()
        return redirect(url_for("bp_users.profile"))

    logbooks = (
        db.session.query(Logbook.id, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )
    return render_template("users/edit.jinja2", pcfg=pcfg, form=form, user=user, logbooks=logbooks)

templates/users/edit.jinja2
{% extends "layout.jinja2" %}
{% import 'bootstrap/form.html' as bf4 %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <h3>Edit profile - {{ current_user.name }}</h3>
        </div>
    </div>

    <form action="{{ url_for('bp_users.edit') }}" method="POST" class="form-horizontal">
        {{ form.hidden_tag() }}
        {{ bf4.form_errors(form, hiddens=True) }}

        <div class="row">
            <div class="col-lg-6">
                {{ bf4.render_field(form.callsign, 'horizontal', class="form-control search-ignore-lastpass") }}
                {{ bf4.render_field(form.locator, 'horizontal', class="form-control search-ignore-lastpass") }}
                {{ bf4.render_field(form.zone, 'horizontal') }}
                {{ bf4.render_field(form.timezone, 'horizontal') }}
                {{ bf4.render_field(form.firstname, 'horizontal', class="form-control search-ignore-lastpass") }}
                {{ bf4.render_field(form.lastname, 'horizontal', class="form-control search-ignore-lastpass") }}
            </div>
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-lg-5">
                        {{ bf4.render_field(form.lotw_name, 'vertical') }}
                        {{ bf4.render_field(form.eqsl_name, 'vertical') }}
                        {{ bf4.render_field(form.hamqth_name, 'vertical') }}
                        {{ bf4.render_field(form.swl, 'vertical') }}
                    </div>
                    <div class="col-lg-6 col-lg-offset-1">
                        {{ bf4.render_field(form.lotw_password, 'vertical') }}
                        {{ bf4.render_field(form.eqsl_password, 'vertical') }}
                        {{ bf4.render_field(form.hamqth_password, 'vertical') }}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                {{ bf4.render_field(form.submit, button_map={'submit': 'success'}) }}
                <a class="btn btn-warning" href="{{ url_for('bp_users.profile') }}">Cancel edit</a>
            </div>
        </div>
    </form>
{% endblock %}

templates/users/profile.jinja2
{% extends "layout.jinja2" %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <h3>{{ current_user.name }}'s profile</h3>
        </div>
    </div>
<div class="row">
    <div class="col-lg-6">
        <table class="table table-sm">
            <tr>
                <td>Username</td>
                <td>{{ current_user.name }}</td>
            </tr>
            <tr>
                <td>Roles</td>
                <td>{{ current_user.join_roles(", ") }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ current_user.email }}</td>
            </tr>
            <tr>
                <td>Callsign</td>
                <td>{{ current_user.callsign or "Please fill me !"}}</td>
            </tr>
            <tr>
                <td>Locator</td>
                <td>{{ current_user.locator or "Please fill me !" }}</td>
            </tr>
            <tr>
                <td>Zone</td>
                <td>{{ current_user.zone_str() }}</td>
            </tr>
            <tr>
                <td>Is a SWL ?</td>
                <td><span class="fa fa-{{ 'ok' if current_user.swl else 'remove' }}"></span></td>
            </tr>
            <tr>
                <td>Timezone</td>
                <td>{{ current_user.timezone }}</td>
            </tr>
            <tr>
                <td>First name</td>
                <td>{{ current_user.firstname or "No firstname defined" }}</td>
            </tr>
            <tr>
                <td>Last name</td>
                <td>{{ current_user.lastname or "No lastname defined"}}</td>
            </tr>
            <tr>
                <td><a class="btn btn-primary" href="{{ url_for('bp_users.edit') }}">Edit profile</a></td>
            </tr>
        </table>
    </div>

    <div class="col-lg-6">
        <table class="table table-sm">
            <tr>
                <td>LoTW</td>
                <td>
                    {% if current_user.lotw_name %}{{ current_user.lotw_name }}{% endif %}
                    {% if current_user.lotw_password %}<span title='Password defined' class="fa fa-lock" aria-hidden="true"></span>{% endif %}
                </td>
            </tr>
            <tr>
                <td>eQSL</td>
                <td>
                    {% if current_user.eqsl_name %}{{ current_user.eqsl_name }}{% endif %}
                    {% if current_user.eqsl_password %}<span title='Password defined' class="fa fa-lock" aria-hidden="true"></span>{% endif %}
                </td>
            </tr>
            <tr>
                <td>HamQTH</td>
                <td>
                    {% if current_user.hamqth_name %}{{ current_user.hamqth_name }}{% endif %}
                    {% if current_user.hamqth_password %}<span title='Password defined' class="fa fa-lock" aria-hidden="true"></span>{% endif %}
                </td>
            </tr>
        </table>
    </div>

</div>
{% endblock %}

templates/users/user_logs.jinja2
{% extends "layout.jinja2" %}

{% block content %}
<div class="row justify-content-between">
    <div class="col-4">
        <h3>{{ current_user.name }}'s logs (latest 100)</h3>
    </div>
    <div class="col-4 text-right">
        Show only:
        <a href="{{ url_for('bp_users.logs') }}" class="btn btn-sm btn-secondary">all</a>
        <a href="{{ url_for('bp_users.logs', level='info') }}" class="btn btn-sm btn-info">info</a>
        <a href="{{ url_for('bp_users.logs', level='warning') }}" class="btn btn-sm btn-warning">warning</a>
        <a href="{{ url_for('bp_users.logs', level='error') }}" class="btn btn-sm btn-danger">error</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <table class="table table-sm table-stripped table-bordered">
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Level</th>
                <th>Logbook</th>
                <th>QSO</th>
                <th>Message</th>
                <th>Actions</th>
            </tr>
            {% for log in logs %}
                <tr>
                    <td width="13%">{{ log.timestamp.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                    <td>{{ log.category }}</td>
                    <td>{{ log.level }}</td>
                    <td>
                        <a href="{{ url_for('bp_qsos.logbook', username=log.user.name, logbook_id=log.logbook.id) }}">{{ log.logbook.id }}</a>
                    </td>
                    <td>
                        {% if log.log %}
                        <a href="{{ url_for('bp_qsos.view', username=log.user.name, logbook_id=log.logbook.id, qso_id=log.log.id) }}">{{ log.log.id }}</a>
                        {% else %}
                            None
                        {% endif %}
                    </td>
                    <td>{{ log.message | replace('\r\n', '<br>') }}</td>
                    <td></td>
                </tr>
            {% endfor %}
        </table>

    </div>
</div>
{% endblock %}