controllers/contacts.py
from libqth import is_valid_qth, qth_to_coords

from flask import Blueprint, render_template, request, redirect, url_for, flash, Response, json
from flask_security import login_required, current_user
from geohelper import distance, bearing
from sqlalchemy import func

from forms import ContactsForm
from libjambon import geo_bearing_star
from models import db, Contact, User, Logbook, Log
from utils import check_default_profile, InvalidUsage

bp_contacts = Blueprint("bp_contacts", __name__)


@bp_contacts.route("/contacts", methods=["GET"])
@login_required
@check_default_profile
def contacts():
    pcfg = {"title": "My contacts"}
    _contacts = Contact.query.filter(Contact.user_id == current_user.id).all()
    logbooks = (
        db.session.query(Logbook.id, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )
    return render_template("contacts/view.jinja2", pcfg=pcfg, contacts=_contacts, logbooks=logbooks)


@bp_contacts.route("/contacts/<int:contact_id>/edit", methods=["GET", "POST"])
@login_required
@check_default_profile
def edit(contact_id):
    pcfg = {"title": "Edit my contacts"}
    a = Contact.query.filter(Contact.id == contact_id, Contact.user_id == current_user.id).first()
    if not a:
        flash("Contact not found", "error")
        return redirect(url_for("bp_contacts.contacts"))

    form = ContactsForm(request.form, obj=a)

    if form.validate_on_submit():
        a.callsign = form.callsign.data
        a.gridsquare = form.gridsquare.data

        if not current_user.locator or not form.gridsquare.data:
            flash("Missing locator_qso or locator_user", "error")
            return redirect(url_for("bp_contacts.contacts"))

        if not is_valid_qth(current_user.locator, 6) or not is_valid_qth(form.gridsquare.data, 6):
            flash("One of the supplied QTH is not valid", "error")
            return redirect(url_for("bp_contacts.contacts"))

        _f = qth_to_coords(current_user.locator, 6)  # precision, latitude, longitude
        _t = qth_to_coords(form.gridsquare.data, 6)  # precision, latitude, longitude

        a.latitude = _t["latitude"]
        a.longitude = _t["longitude"]
        a.distance = distance.haversine_km(_f["latitude"], _f["longitude"], _t["latitude"], _t["longitude"])
        a.bearing = bearing.initial_compass_bearing(_f["latitude"], _f["longitude"], _t["latitude"], _t["longitude"])
        a.bearing_star = geo_bearing_star(a.bearing)

        db.session.commit()
        flash("Success saving contact: {0}".format(a.callsign), "success")
        return redirect(url_for("bp_contacts.contacts"))

    logbooks = (
        db.session.query(Logbook.id, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )
    return render_template(
        "contacts/edit.jinja2", pcfg=pcfg, form=form, contact=a, contact_id=contact_id, logbooks=logbooks
    )


@bp_contacts.route("/contacts/new", methods=["GET", "POST"])
@login_required
@check_default_profile
def new():
    pcfg = {"title": "New contact"}

    form = ContactsForm()

    if form.validate_on_submit():
        a = Contact()
        a.callsign = form.callsign.data
        a.gridsquare = form.gridsquare.data

        if not current_user.locator or not form.gridsquare.data:
            flash("Missing locator_qso or locator_user", "error")
            return redirect(url_for("bp_contacts.contacts"))

        if not is_valid_qth(current_user.locator, 6) or not is_valid_qth(form.gridsquare.data, 6):
            flash("One of the supplied QTH is not valid", "error")
            return redirect(url_for("bp_contacts.contacts"))

        _f = qth_to_coords(current_user.locator, 6)  # precision, latitude, longitude
        _t = qth_to_coords(form.gridsquare.data, 6)  # precision, latitude, longitude

        a.latitude = _t["latitude"]
        a.longitude = _t["longitude"]
        a.distance = distance.haversine_km(_f["latitude"], _f["longitude"], _t["latitude"], _t["longitude"])
        a.bearing = bearing.initial_compass_bearing(_f["latitude"], _f["longitude"], _t["latitude"], _t["longitude"])
        a.bearing_star = geo_bearing_star(a.bearing)

        a.user_id = current_user.id

        db.session.add(a)
        db.session.commit()
        flash("Success updating contact: {0}".format(a.callsign), "success")
        return redirect(url_for("bp_contacts.contacts"))

    logbooks = (
        db.session.query(Logbook.id, Logbook.name, func.count(Log.id))
        .join(Log)
        .filter(Logbook.user_id == current_user.id)
        .group_by(Logbook.id)
        .all()
    )
    return render_template("contacts/new.jinja2", pcfg=pcfg, form=form, logbooks=logbooks)


@bp_contacts.route("/contacts/<int:contact_id>/delete", methods=["GET", "DELETE", "PUT"])
@login_required
@check_default_profile
def delete(contact_id):
    contact = Contact.query.filter(Contact.id == contact_id, Contact.user_id == current_user.id).first()
    if not contact:
        flash("Contact not found", "error")
        return redirect(url_for("bp_contacts.contacts"))

    db.session.delete(contact)
    db.session.commit()
    flash("Success deleting contact: {0}".format(contact.callsign), "success")
    return redirect(url_for("bp_contacts.contacts"))


@bp_contacts.route("/contacts/<string:username>/geojson", methods=["GET"])
def contacts_geojson(username):
    if not username:
        raise InvalidUsage("Missing username", status_code=400)

    user = User.query.filter(User.name == username).first()
    if not user:
        raise InvalidUsage("User not found", status_code=404)

    _contacts = Contact.query.filter(User.id == user.id).all()

    if not is_valid_qth(user.locator, 6):
        raise InvalidUsage("QTH is not valid", status_code=400)
    _u = qth_to_coords(user.locator, 6)  # precision, latitude, longitude

    j = [
        {
            "type": "Feature",
            "properties": {"name": user.cutename(), "callsign": user.callsign, "own": True, "icon": "home"},
            "geometry": {"type": "Point", "coordinates": [_u["longitude"], _u["latitude"]]},
        }
    ]

    for log in _contacts:
        if log.gridsquare:
            if not is_valid_qth(log.gridsquare, 6):
                raise InvalidUsage("QTH is not valid", status_code=400)
            _f = qth_to_coords(log.gridsquare, 6)  # precision, latitude, longitude
        else:
            _f = log.country_grid_coords()
            if not _f:
                continue  # No grid at all ? Skit ip

        f = {
            "type": "Feature",
            "properties": {
                "callsign": log.callsign,
                "distance": log.distance,
                "bearing": log.bearing,
                "bearing_star": log.bearing_star,
                "icon": "qso",
            },
            "geometry": {"type": "Point", "coordinates": [_f["longitude"], _f["latitude"]]},
        }
        j.append(f)

    return Response(json.dumps(j), mimetype="application/json")

templates/contacts/edit.jinja2
{% extends "layout.jinja2" %}
{% import 'bootstrap/form.html' as bf4 %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h3>Edit contact: {{ contact.callsign }} <a class="btn btn-sm btn-warning" href="{{ url_for('bp_contacts.contacts') }}">Cancel</a></h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12">
            {{ bf4.render_form(form, action=url_for('bp_contacts.edit', contact_id=contact.id), horizontal_columns=('lg', 2, 4), form_type='horizontal', button_map={'submit': 'success'}) }}
        </div>
    </div>
{% endblock %}

templates/contacts/new.jinja2
{% extends "layout.jinja2" %}
{% import 'bootstrap/form.html' as bf4 %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h3>New contact <a class="btn btn-sm btn-warning" href="{{ url_for('bp_contacts.contacts') }}">Cancel</a></h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12">
            {{ bf4.render_form(form, action=url_for('bp_contacts.new'), horizontal_columns=('lg', 2, 4), form_type='horizontal', button_map={'submit': 'success'}) }}
        </div>
    </div>
{% endblock %}

templates/contacts/view.jinja2
{% extends "layout.jinja2" %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h3>
            {{ current_user.name }}'s contacts
            <a href="{{ url_for('bp_contacts.new') }}" class="btn btn-success btn-sm">new</a>
        </h3>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">

        <table class="table table-sm contacts-list">
            <tr>
                <th>Callsign</th>
                <th>Gridsquare</th>
                <th>Distance</th>
                <th>Bearing</th>
                <th>Dir</th>
                {% if current_user.is_authenticated %}
                    <th>Actions</th>
                {% endif %}
            </tr>
            {% for c in contacts %}
                <tr>
                    <td>{{ c.callsign }}</td>
                    <td>{{ c.gridsquare }}</td>
                    <td>{{ c.distance | round}} Km</td>
                    <td>{{ c.bearing | round}}</td>
                    <td>{{ c.bearing_star }}</td>
                    {% if current_user.is_authenticated %}
                        <td>
                            <a href="{{ url_for('bp_contacts.edit', contact_id=c.id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            &nbsp;&nbsp;
                            <a href="{{ url_for('bp_contacts.delete', contact_id=c.id) }}" class="delete_link"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>

    </div>
    <div class="col-lg-6">
        <div id="map" style="height: 300px"></div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/leaflet.js') }}"></script>
    <script src="{{ url_for('static', filename='js/leaflet-providers.js') }}"></script>
    <script src="{{ url_for('static', filename='js/leaflet.ajax.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/leaflet.awesome-markers.js') }}"></script>

    <script>
        var map = L.map('map').setView([52, 4], 3);
        map.addLayer(L.tileLayer.provider('OpenStreetMap.Mapnik'));

        function popUp(f,l){
            var out = [];
            if (f.properties) {
                if (f.properties['own']) {
                    l.bindPopup("<div class='popupMap'>This user: " + f.properties['callsign'] + "</div>")
                } else {
                    var string = "Callsign: " + f.properties['callsign'];
                    string += "<br />Distance: " + Math.round(f.properties['distance']) + " Km";
                    string += "<br />Bearing: " + Math.round(f.properties['bearing']) + " " + f.properties['bearing_star'];
                    l.bindPopup("<div class='popupMap'>" + string + '</div>');
                }

                if (f.properties['icon'] == 'home') {
                    l.setIcon(homeIcon);
                } else if (f.properties['icon'] == 'qso') {
                    l.setIcon(qsoIcon);
                } else {
                    l.setIcon(defaultIcon);
                }
            }
        }

        var defaultIcon = L.AwesomeMarkers.icon({
            icon: 'star',
            markerColor: 'blue'
        });
        var qsoIcon = L.AwesomeMarkers.icon({
            icon: 'user',
            markerColor: 'blue'
        });
        var homeIcon = L.AwesomeMarkers.icon({
            icon: 'home',
            markerColor: 'green'
        });

        var geojsonLayer = new L.GeoJSON.AJAX(["{{ url_for('bp_contacts.contacts_geojson', username=current_user.name) }}"],{onEachFeature:popUp}).addTo(map);

    </script>
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/leaflet.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/leaflet.awesome-markers.css') }}" />
{% endblock %}